Repository replicatedhq/replicated-actions, pull requests merged in 2024-05, with the labels that each got.

#55 chore: upgrade to replicated-lib 0.0.1-beta.14
  archive-channel/dist/index.js
  archive-channel/dist/index.js.map
  archive-channel/package-lock.json
  archive-channel/package.json
  archive-customer/dist/index.js
  archive-customer/dist/index.js.map
  archive-customer/package-lock.json
  archive-customer/package.json
  create-cluster/dist/index.js
  create-cluster/dist/index.js.map
  create-cluster/package-lock.json
  create-cluster/package.json
  create-customer/dist/index.js
  create-customer/dist/index.js.map
  create-customer/package-lock.json
  create-customer/package.json
  create-object-store/dist/index.js
  create-object-store/dist/index.js.map
  create-object-store/package-lock.json
  create-object-store/package.json
  create-postgres/dist/index.js
  create-postgres/dist/index.js.map
  create-postgres/package-lock.json
  create-postgres/package.json
  create-release/dist/index.js
  create-release/dist/index.js.map
  create-release/package-lock.json
  create-release/package.json
  expose-port/dist/index.js
  expose-port/dist/index.js.map
  expose-port/package-lock.json
  expose-port/package.json
  get-customer-instances/dist/index.js
  get-customer-instances/dist/index.js.map
  get-customer-instances/package-lock.json
  get-customer-instances/package.json
  promote-release/dist/index.js
  promote-release/dist/index.js.map
  promote-release/package-lock.json
  promote-release/package.json
  remove-cluster/dist/index.js
  remove-cluster/dist/index.js.map
  remove-cluster/package-lock.json
  remove-cluster/package.json
  report-compatibility-result/dist/index.js
  report-compatibility-result/dist/index.js.map
  report-compatibility-result/package-lock.json
  report-compatibility-result/package.json
  upgrade-cluster/dist/index.js
  upgrade-cluster/dist/index.js.map
  upgrade-cluster/package-lock.json
  upgrade-cluster/package.json
Labels: bug::normal, type::bug

#57 chore: upgrade to replicated-lib 0.0.1-beta.16
  archive-channel/dist/index.js
  archive-channel/dist/index.js.map
  archive-channel/package-lock.json
  archive-channel/package.json
  archive-customer/dist/index.js
  archive-customer/dist/index.js.map
  archive-customer/package-lock.json
  archive-customer/package.json
  create-cluster/dist/index.js
  create-cluster/dist/index.js.map
  create-cluster/package-lock.json
  create-cluster/package.json
  create-customer/dist/index.js
  create-customer/dist/index.js.map
  create-customer/package-lock.json
  create-customer/package.json
  create-object-store/dist/index.js
  create-object-store/dist/index.js.map
  create-object-store/package-lock.json
  create-object-store/package.json
  create-postgres/dist/index.js
  create-postgres/dist/index.js.map
  create-postgres/package-lock.json
  create-postgres/package.json
  create-release/dist/index.js
  create-release/dist/index.js.map
  create-release/package-lock.json
  create-release/package.json
  expose-port/dist/index.js
  expose-port/dist/index.js.map
  expose-port/package-lock.json
  expose-port/package.json
  get-customer-instances/dist/index.js
  get-customer-instances/dist/index.js.map
  get-customer-instances/package-lock.json
  get-customer-instances/package.json
  promote-release/dist/index.js
  promote-release/dist/index.js.map
  promote-release/package-lock.json
  promote-release/package.json
  remove-cluster/dist/index.js
  remove-cluster/dist/index.js.map
  remove-cluster/package-lock.json
  remove-cluster/package.json
  report-compatibility-result/dist/index.js
  report-compatibility-result/dist/index.js.map
  report-compatibility-result/package-lock.json
  report-compatibility-result/package.json
  upgrade-cluster/dist/index.js
  upgrade-cluster/dist/index.js.map
  upgrade-cluster/package-lock.json
  upgrade-cluster/package.json
Labels: bug::regression, type::bug

#58 Fix boolean input for is kots install enabled
  create-customer/README.md
  create-customer/action.yml
Labels: bug::regression, type::bug

#61 fix is kots install enabled default true
  create-customer/README.md
  create-customer/action.yml
  create-customer/dist/index.js
  create-customer/dist/index.js.map
  create-customer/src/index.ts
Labels: bug::regression, type::bug

#64 Add ip-family
  .gitignore
  archive-channel/dist/index.js
  archive-channel/dist/index.js.map
  archive-customer/dist/index.js
  archive-customer/dist/index.js.map
  create-cluster/README.md
  create-cluster/action.yml
  create-cluster/dist/index.js
  create-cluster/dist/index.js.map
  create-customer/dist/index.js
  create-customer/dist/index.js.map
  create-object-store/dist/index.js
  create-object-store/dist/index.js.map
  create-postgres/dist/index.js
  create-postgres/dist/index.js.map
  create-release/dist/index.js
  create-release/dist/index.js.map
  expose-port/dist/index.js
  expose-port/dist/index.js.map
  get-customer-instances/dist/index.js
  get-customer-instances/dist/index.js.map
  get-customer-instances/package-lock.json
  get-customer-instances/package.json
  helm-install/dist/index.js
  helm-install/dist/index.js.map
  kots-install/dist/index.js
  kots-install/dist/index.js.map
  package-lock.json
  package.json
  prepare-cluster/README.md
  prepare-cluster/action.yml
  prepare-cluster/dist/index.js
  prepare-cluster/dist/index.js.map
  promote-release/dist/index.js
  promote-release/dist/index.js.map
  promote-release/package-lock.json
  promote-release/package.json
  remove-cluster/dist/index.js
  remove-cluster/dist/index.js.map
  report-compatibility-result/dist/index.js
  report-compatibility-result/dist/index.js.map
  report-compatibility-result/package-lock.json
  report-compatibility-result/package.json
  src/create-cluster/index.ts
  upgrade-cluster/dist/index.js
  upgrade-cluster/dist/index.js.map
  upgrade-cluster/package-lock.json
  upgrade-cluster/package.json
Labels: type::feature

#65 fix(kots-install): incorrect path to main
  .github/workflows/test-kots-install.yml
  kots-install/action.yml
Labels: bug::regression, type::bug

#66 fix: description readme ip-family
  create-cluster/README.md
  create-cluster/action.yml
  prepare-cluster/README.md
  prepare-cluster/action.yml
Labels: bug::normal, type::bug

#68 fix(helm-install): registry login not required
  .github/workflows/test-helm-install.yml
  archive-channel/dist/index.js
  archive-channel/dist/index.js.map
  archive-customer/dist/index.js
  archive-customer/dist/index.js.map
  create-cluster/dist/index.js
  create-cluster/dist/index.js.map
  create-customer/dist/index.js
  create-customer/dist/index.js.map
  create-object-store/dist/index.js
  create-object-store/dist/index.js.map
  create-postgres/dist/index.js
  create-postgres/dist/index.js.map
  create-release/dist/index.js
  create-release/dist/index.js.map
  expose-port/dist/index.js
  expose-port/dist/index.js.map
  helm-install/README.md
  helm-install/action.yml
  helm-install/dist/index.js
  helm-install/dist/index.js.map
  kots-install/dist/index.js
  kots-install/dist/index.js.map
  prepare-cluster/dist/index.js
  prepare-cluster/dist/index.js.map
  remove-cluster/dist/index.js
  remove-cluster/dist/index.js.map
  src/helm-install/index.ts
Labels: bug::regression, type::bug
